name: ${COMPOSE_PROJECT_NAME:-envdemo_staging}

services:
  backend_staging:
    build: ./backend
    container_name: backend_staging
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      CORS_ORIGINS: ${CORS_ORIGINS}
      API_TOKEN_SECRET_PATH: /run/secrets/api_token_secret
      DB_PASSWORD_SECRET_PATH: /run/secrets/db_password
    volumes:
      - data_staging:/data
      - ./secrets/staging/api_token_secret.txt:/run/secrets/api_token_secret:ro
      - ./secrets/staging/db_password.txt:/run/secrets/db_password:ro
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - staging_net

  frontend_staging:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_APP_ENV: ${VITE_APP_ENV}
    container_name: frontend_staging
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - staging_net
